#!/bin/perl
if ($ARGV[0]) {
  open(WORDS, "+<$ARGV[0]");
} else {
  open(WORDS, "+<../dictionary_files/large_dictionary.txt");
}

@words = <WORDS>;

close(WORDS);

foreach $li (@words) {
  chomp $li;
  if ( $li =~ m/(^([qwertasdfgzxcvb][yuiophjklnm])+$)|(^([yuiophjklnm][qwertasdfgzxcvb])+$)/ ) {
    if ( length($li) >= 6 ) {
      print "$li\n";
    }
#  } else {
#    print "$li\n";
  }
}

