#!/bin/perl

open(WORDS, "+<../dictionary_files/dictionary.txt");

@words = <WORDS>;

close(WORDS);

foreach $li (@words) {
  chomp $li;
  if ( $li =~ m/(^([qwertasdfgzxcvb][yuiophjklnm])+$)|(^([yuiophjklnm][qwertasdfgzxcvb])+$)/ ) {
    if ( length($li) >= 6 ) {
      print "$li\n";
    }
#  } else {
#    print "$li\n";
  }
}

