#!/usr/bin/perl
# By Lily Williamson
# This is a bit of a disaster but it works!
# If you use this to generate a dictionary file and then 
#  point passwordgen.sh at it, you can make secure passwords that are
#  (mostly) pronounceable but aren't dictionary words.
# All options are optional.
# Example command: ./genfakewords -1000 -m 6 -M 12 -i my_dict.txt -o output.txt
# -1000 means it'll give you 1000 fake words - default 25
# -m 6 -M 12 will give you words 6-12 characters long - default 5-10
# -i optionally lets you pick an input dictionary to have the script learn what words are
# -o optionally lets you direct output to somewhere other than stdout

use Getopt::Long;

our $min_length  = 5;
our $max_length  = 10;
$file        = "../dictionary_files/large_dictionary.txt";
$outfile     = undef;
$show_hash   = 0;
$number      = 25;

# capture any input number before GetOptions
for (my $i = $#ARGV; $i >= 0; $i--) {
    if ($ARGV[$i] =~ /^-(\d+)$/) {
        $number = $1;
        splice(@ARGV, $i, 1);
    }
}
GetOptions(
    "m=i"           => \$min_length,
    "M=i"           => \$max_length,
    "i|input-file=s"  => \$file,
    "o|output-file=s" => \$outfile,
    "s"             => \$show_hash,
) or die "Usage: $0 [-#] [-m min] [-M max] [-i input] [-o output] [-s]\n";

if ($outfile) {
    open(STDOUT, ">", $outfile) or die "Can't open output file $outfile: $!";
}
if ($show_hash) {
    # (Hash loading logic would need to happen before this)
    # This matches your original logic flow
    $number = 's'; 
}
srand(time);

# Read in the data, cleaning it up as we go, and making it one long array
open(INFILE, "<", $file) or die "$0: $file not found: $!\n";
while (<INFILE>) {
  s/#.*//;
  next unless /\S/; # Skip empty/whitespace lines
  s/^\s*//; 
  s/\s*\n//; 
  s/ +/ /g;
  push(@data, ' ', split('', $_)); 
}
close(INFILE);

# Let's assume the first letter could follow the last pair (loop around)
push(@data, ' ', $data[1]);

# Now, load our hash of character pairs and the letters that may follow them,
# keeping track of which pairs can be at the start of a word
while (@data > 2) {
  ($first, $second, $third) = @data[0..2];
  $hash{$first.$second} .= $third;
  push(@start_pairs, $second.$third) if ($first eq ' ');
  shift @data; 
}

# Oh, so you just want to see a representation of our hash??? OK.
($number eq 's') and (print map { "$_:$hash{$_}\n" } keys %hash) and exit;

# Loop to generate new words, beginning with a start_pair; find a word,
# then continue to the next word using the last two characters (the last
# of which will be whitespace) from the previous word as a "seed" for the new;
# oh, and only print the first $max_length characters of any words
$new = $start_pairs[rand @start_pairs];
for (1..$number) {
  $new = &new_word(substr($new, -2, 2));
  print substr($new, 0, $max_length), "\n";
}

# Messy recursive function to build a word, getting rid of short words 
# and handling "seeds" from previous words properly
sub new_word {
  my $word = @_;
  my $pair = substr($word, -2, 2);
  my $letter = substr($hash{$pair}, rand length($hash{$pair}), 1);
  if ($letter =~ /\s$/) {
    return substr($word, 0, $max_length) if (length($word) >= $min_length);
    $word =~ s/^\s+//;
    return &new_word($word);
  } else {
    $word =~ s/^\s//;
    return &new_word($word.$letter);
  }
}
