#!/usr/bin/perl
# By Lily Williamson
# This is a bit of a disaster but it works!
# If you use this to generate a dictionary file and then 
#  point passwordgen.sh at it, you can make secure passwords that are
#  (mostly) pronounceable but aren't dictionary words.
# All options are optional.
# Example command: ./genfakewords -1000 -m 6 -M 12 -i my_dict.txt -o output.txt
# -1000 means it'll give you 1000 fake words - default 25
# -m 6 -M 12 will give you words 6-12 characters long - default 5-10
# -i optionally lets you pick an input dictionary to have the script learn what words are
# -o optionally lets you direct output to somewhere other than stdout

$file = '../dictionary_files/large_dictionary.txt';
$number = 25;
$min_length = 5;
$max_length = 10;
while (@ARGV) {
    $_ = shift @ARGV;
    if (/^-(\d+)$/)      { $number = $1; }
    elsif (/^-m$/)       { $min_length = shift @ARGV; }
    elsif (/^-M$/)       { $max_length = shift @ARGV; }
    elsif (/^-i$/)       { $file = shift @ARGV; }
    elsif (/^-o$/)       { $outfile = shift @ARGV; open(STDOUT, ">$outfile"); }
    elsif (/^-s$/)       { $number = 's'; }
    elsif (!/^-/)        { $file = $_; } # Fallback for positional filename
}
$number = 's' if $show_hash;
$number =~ s/-//;
if ($outfile) {
    open(STDOUT, ">", $outfile) or die "Can't open $outfile: $!";
}
srand(time);

# Read in the data, cleaning it up as we go, and making it one long array
open(INFILE, $file) or die "$0: $file not found\n";
while (<INFILE>) {
  s/#.*//;
  next unless length;
  s/^\s*//;
  s/\s*\n//;
  s/\s+/ /;
  push(@data, ' ', split('', $_));
}
# Let's assume the first letter could follow the last pair (loop around)
push(@data, ' ', $data[1]);

# Now, load our hash of character pairs and the letters that may follow them,
# keeping track of which pairs can be at the start of a word
while (@data > 2) {
  ($first, $second, $third) = @data[0..2];
  $hash{$first.$second} .= $third;
  push(@start_pairs, $second.$third) if ($first eq ' ');
  shift @data;
}

# Oh, so you just want to see a representation of our hash??? OK.
($number eq 's') and (print map { "$_:$hash{$_}\n" } keys %hash) and exit;

# Loop to generate new words, beginning with a start_pair; find a word,
# then continue to the next word using the last two characters (the last
# of which will be whitespace) from the previous word as a "seed" for the new;
# oh, and only print the first $max_length characters of any words
$new = $start_pairs[rand @start_pairs];
for (1..$number) {
  $new = &new_word(substr($new, -2, 2));
  print substr($new, 0, $max_length), "\n";
}

# Messy recursive function to build a word, getting rid of short words
# and handling seeds from previous words
sub new_word {
  my $word = pop;
  my $pair = substr($word, -2, 2);
  my $letter = substr($hash{$pair}, rand length($hash{$pair}), 1);
  if ($word =~ /\s$/) {
    return $word if (length($word) > $min_length);
    return &new_word(substr($word, -1, 1).$letter);
  } else {
    $word =~ s/^\s//;
    return &new_word($word.$letter);
  }
}
